sonar.projectKey=ankur_project
sonar.projectName=My project
sonar.projectVersion=1.0
sonar.sources=srcDir1,srcDir2
sonar.tests=testDir1,testDir2
sonar.sources=.
sonar.host=http://localhost:8081
sonar.login=sqa_9e0aaaf3147b76768be800ed8226e79595707031
